name: Lint and Format

on:
  pull_request:
    branches:
      - dev
      - prod
  push:
    branches:
      - dev
      - prod

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run Ruff linter
        run: |
          ruff check .

      - name: Check formatting with Ruff
        run: |
          ruff format --check .
